### ISSUE TITLE
StreamTokenizer, StreamTreeConstructor missing from index.d.ts

### ISSUE THREAD

**Issue by ejoebstl** [mykolaharmash/hyntax#17]
`StreamTokenizer` and `StreamTreeConstructor` are missing from the typescript definitions in `index.d.ts`.

It would be super sweet to have them there out of the box.

**Comment by nik-garmash** [comment]
Hi, thanks for the report, I missed them somehow, will add 👍

**Comment by mykolaharmash** [comment]
Sorry, I procrastinated this for that long, v1.1.2 with the fix is now published.
