### ISSUE TITLE
Does this support browser environment ?

### ISSUE THREAD

**Issue by dimensi** [mykolaharmash/hyntax#39]
I wrote xhtml2pug library to convert pug to html. I've test it in codesandbox and it works well https://codesandbox.io/s/vibrant-clarke-whgj4?file=/src/index.js but I can't start with parcel or vite.
Do you know how to resolve this problem?

**Comment by mykolaharmash** [comment]
Hey! Thank you for reporting this, I have not tried to build it with Parcel yet. Will try today/tomorrow and get back to you.

**Comment by mykolaharmash** [comment]
In the meantime, could you show some error messages or other output you get when the build fails?

**Comment by mykolaharmash** [comment]
Ok, just tried to build with Parcel the same app you have in codesandbox. Locally everything works fine, let's see the errors you get on your side.

The app I'm building, just in case:
```
import { convert } from "xhtml2pug";

const inputHTML = `
<h1>Hello Vanilla!</h1>
<div>
  We use the same configuration as Parcel to bundle this sandbox, you can find more
  info about Parcel 
  <a href="https://parceljs.org" target="_blank" rel="noopener noreferrer">here</a>.
</div>
`

const pug = convert(inputHTML)

console.log(pug)
```

**Comment by dimensi** [comment]
Well.... idk what the shit happens. But now it's working...
But parcel polyfills stream api with stream-browserfily. 
![image](https://user-images.githubusercontent.com/11390039/106387988-81bd5500-63ed-11eb-99e2-e948c437dc55.png)
But sometimes he cannot do this and throw error in StreamTokinizer.

**Comment by mykolaharmash** [comment]
Hm... ok, good that it works now, but Parcel should not even bundle stream polyfills as you are not using them, stream modules in Hytax are completely decoupled. I'll figure this out, maybe I messed up the way I expose the modules.

In the meantime you can change hyntax imports in your package to be:
```
const tokenize = require('hyntax/lib/tokenize')
const constructTree = require('hyntax/lib/construct-tree')
```

This way Parcel will not bundle anything extra for sure. Could you try and tell me if it works for you?

**Comment by dimensi** [comment]
Yep, i'll try.

**Comment by dimensi** [comment]
I not sure help it or not.
![image](https://user-images.githubusercontent.com/11390039/106388751-fd6cd100-63f0-11eb-8603-ed15cf13e882.png)

Could you plz don't close issue? I'll try working on this.
Also thanks, you're the best.

**Comment by mykolaharmash** [comment]
No problem, I'll keep the issue open 👍

Seems like it helped, there are not plyfills in the bundle, so you should not get that error anymore and your package bandle should be a bit smaller now as a side effect.

**Comment by dimensi** [comment]
Thanks, now my home project can work without backend :tada:
https://html2pug.now.sh/
