### ISSUE TITLE
Self-close tags

### ISSUE THREAD

**Issue by dimensi** [mykolaharmash/hyntax#40]
As I see hyntax cannot parse self-close custom tags https://astexplorer.net/#/gist/1f1cf8a9a27f821c3a0273dc5b269036/71c30bb3d449100886cb2ebf0a594fdd54135e38 ?
Do you plan any support of this?

**Comment by mykolaharmash** [comment]
Those are not really part of [the HTML standard](https://html.spec.whatwg.org/multipage/syntax.html#elements-2), the only possible self-closing tags by the specs are so-called void elements, which are `area, base, br, col, embed, hr, img, input, link, meta, param, source, track, wbr`. So unless HTML standard changes, I'm not going to add support for this.

One thing you could do, even though it's not easy, is to create a custom tree constructor. `tokenize()` function returns an array of raw tokens and you can pass this array to a custom AST builder that supports custom syntax like `<custom-tag />`.

**Comment by mykolaharmash** [comment]
You can check that browsers also don't support such syntax.

Code:
![CleanShot 2021-02-01 at 11 55 39](https://user-images.githubusercontent.com/793851/106449712-8b45cc00-6484-11eb-88cb-afcbc428ef5d.png)

Browser output:
![CleanShot 2021-02-01 at 11 55 55](https://user-images.githubusercontent.com/793851/106449730-91d44380-6484-11eb-9c7e-28a55a4dd16d.png)

Don't know what is your exact usecase, but might be you don't even need such tags as browsers won't be able to parse them correctly.

**Comment by dimensi** [comment]
Well It's for vue, angular frameworks. But anyway thank you.

**Comment by dimensi** [comment]
But I want to note that the parser stopped parsing html at one point when it encountered an unregistered void tag. The readme.md says that you can write any invalid html)

**Comment by mykolaharmash** [comment]
Yes, it should continue parsing anyway. Could you provide HTML you're trying to parse?

**Comment by mykolaharmash** [comment]
> Well It's for vue, angular frameworks. But anyway thank you.

Ok, I understand. Those frameworks, along with React's JSX use their own custom syntax, which looks like an HTML but with additional features outside of HTML specs. They use their own custom parsers.

**Comment by dimensi** [comment]
Oh, sorry. I looked up in the ast tree better and not found a mistake.
I close this issue. I think I need to change parser because of my circumstances
